# NumPy Matris Oluşturma Örnekleri

In [1]:
import numpy as np

In [6]:
# 1) Tek boyutlu array (vektör gibi)
a = np.array([5, 7, 3, 4]) # 1 boyutlu array (4 eleman)
print(a)
a.shape

[5 7 3 4]


(4,)

In [7]:
# 2) İki boyutlu array   1 satır 4 sutun
b = np.array([[5,7,4,3]])
print(b)
b.shape

[[5 7 4 3]]


(1, 4)

**Yukarıdaki örnekte dikkat! İkisinde de içerideki liste aynı ama birinde tek boyutlu diğerinde 2 boyutlu nump array oluşuyor!**

In [9]:
# 3) İki boyutlu array  2 satır 1 sütun
c = np.array([[7],[8]])
print(c)
c.shape

[[7]
 [8]]


(2, 1)

In [10]:
# 4) İki boyutlu array   2x2 matris
d = np.array([[1,2],[3,4]])
print(d)
d.shape

[[1 2]
 [3 4]]


(2, 2)

In [11]:
# 5) İki boyutlu array   2x3 matris
e = np.array([[1,2,3],[4,5,6]])
print(e)
e.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [14]:
# 6) Birim matris (eye)
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# 7) Sıfır ve birlerle matris
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
# 8) Random matris
rand_m = np.random.randint(50,100,(2,3))   # 2x3 rastgele tam sayılarla matris
print(rand_m)

[[50 66 69]
 [57 82 54]]
