# NumPy Array Oluşturma Örnekleri

NumPy'da array oluşturmanın birden fazla yöntemi mevcuttur. Ancak kendi belirlediğiniz spesifik değerler içeren özel bir numpy array oluşturabilmeniz için mutlaka ya bir list ya da tuple kullanmanız gerekmektedir.

In [30]:
import numpy as np

In [31]:
# 1) Liste veya tupledan array oluşturma
arr1 = np.array([1, 3, 87, 44])  # listeden

In [32]:
type(arr1)

numpy.ndarray

In [33]:
arr2 = np.array((10, 20, 30)) # tupledan

In [34]:
type(arr2)

numpy.ndarray

In [35]:
print(arr1)
print(arr2)

[ 1  3 87 44]
[10 20 30]


In [36]:
# 2) Çok boyutlu array
arr3 = np.array([[1,2,3],[4,5,6]]) # 2x3 array
print(arr3)

[[1 2 3]
 [4 5 6]]


In [37]:
type(arr3)

numpy.ndarray

In [38]:
arr3.shape

(2, 3)

In [39]:
listx = [[1,2,3],[4,5,6]]

In [40]:
listy = [[10,20,30],[40,50,60]]

In [41]:
listz = listx + listy
print(listz)

[[1, 2, 3], [4, 5, 6], [10, 20, 30], [40, 50, 60]]


In [42]:
arr4 = np.array([[10,20,30],[40,50,60]])

In [43]:
arr5 = arr4 + arr3
print(arr5)

[[11 22 33]
 [44 55 66]]


In [44]:
print(arr4)

[[10 20 30]
 [40 50 60]]


In [45]:
# 3) Sıfır, bir değerleriyle dolu ve boş array oluşturma

In [46]:
z = np.zeros((2,3)) # 2x3 sıfırlar
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [47]:
o = np.ones((3,2))  # 3x2 birler
print(o)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [48]:
e = np.empty((2,2))  # 2x2 boş (rastgele değerler gelebilir)
print(e)

[[4.94e-324 1.48e-323]
 [4.30e-322 2.17e-322]]


In [49]:
e[0][0]= 40
print(e)

[[4.00e+001 1.48e-323]
 [4.30e-322 2.17e-322]]


In [50]:
z[1,1] = 5
print(z)

[[0. 0. 0.]
 [0. 5. 0.]]


In [51]:
w = np.zeros(5) # varsayılan olarak dtype = float olur yani 0.0
print(w)

[0. 0. 0. 0. 0.]


In [52]:
w[0] = 8
print(w)
type(w[0])

[8. 0. 0. 0. 0.]


numpy.float64

In [53]:
w2 = np.zeros(5,dtype=int)
print(w2)
type(w2[0])

[0 0 0 0 0]


numpy.int64

In [54]:
w2[0] = 9
print(w2)

[9 0 0 0 0]


In [55]:
# 4) Sayı aralıklarıyla array
a1 = np.arange(0, 10, 2) # 0'dan 10'a  kadar 2şer
print(a1)

[0 2 4 6 8]


In [56]:
s2 = np.linspace(0, 1, 5) # 0 ile 1 arasındaki 5 sayı
print(s2)

[0.   0.25 0.5  0.75 1.  ]


In [57]:
# 5) Rastgele (Random) array
r1 = np.random.rand(2,3) # 2x3, 0-1 arası float değerlerle
print(r1)

[[0.64524365 0.995278   0.46332283]
 [0.1207797  0.69907797 0.04784522]]


In [59]:
r2 = np.random.randint(0,10,(2,3))  # 2x3 luk 0-9 arası integer 
print(r2)

[[7 0 5]
 [2 3 4]]


In [63]:
# 6) dtype (veri tipi) ile array
arr4 = np.array([4.3, 7, 3],dtype=float)  # float tipinde
print(arr4)

[4.3 7.  3. ]


In [64]:
arr5 = np.array([4, 7, 3],dtype=int) # int tipinde
print(arr5)

[4 7 3]


In [65]:
arr_bool = np.array([1, 0, 1],dtype=bool)  # bool tipinde
print(arr_bool)

[ True False  True]


In [68]:
# 7) dtype kullanmazsanız
arr7 = np.array([1, 2, 3])  # int yapar dtype vermezsek
print(arr7,type(arr7[0]))


[1 2 3] <class 'numpy.int64'>


In [69]:
arr7.shape

(3,)

In [70]:
r2.shape

(2, 3)