# NumPy Dizilerde İndeksleme ve Seçim

In [3]:
import numpy as np

### 1) Tek boyutlu dizilerde indeksleme

In [4]:
a = np.array([10, 20, 30, 40, 50])
print(a)

[10 20 30 40 50]


In [6]:
print("İlk eleman : ",a[0])  # 0. indeks

İlk eleman :  10


In [7]:
print("Son eleman : ",a[4])  # 4. indeks

Son eleman :  50


In [10]:
print("? eleman : ",a[-2]) 

? eleman :  40


### 2) Tek boyutlu dizilerde dilimleme (slice)

In [11]:
print("İlk üç eleman:", a[:3]) # 0 - 2 arası

İlk üç eleman: [10 20 30]


In [14]:
print("Ortadaki elemanlar",a[1:4]) # 1- 3 arası

Ortadaki elemanlar [20 30 40]


In [17]:
print("2 adım atlayarak:", a[::2]) # 0 , 2, 4. indexler

2 adım atlayarak: [10 30 50]


In [18]:
print("2 adım atlayarak birinciden başlayarak:", a[1::2]) #

2 adım atlayarak birinciden başlayarak: [20 40]


### 3) İki boyutlu dizilerde indexleme

In [19]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print("0. satır, 1. sütun :",b[0,1]) # tek eleman

0. satır, 1. sütun : 2


In [22]:
print("2. satırın tamamı: ",b[1]) # tek satır

2. satırın tamamı:  [4 5 6]


In [23]:
print("0. sütun: ",b[:,0]) # tek sütun

0. sütun:  [1 4 7]


### 4) 2 Boyutlu dizilerde dilimleme

In [24]:
print("İlk 2 satır ilk 2 sütun:\n",b[:2,:2])

İlk 2 satır ilk 2 sütun:
 [[1 2]
 [4 5]]


In [27]:
print("Son 2 sütun :\n",b[:,1:])

Son 2 sütun :
 [[2 3]
 [5 6]
 [8 9]]


### 5) Mantıksal seçim (Boolean Indexing)

In [28]:
c = np.array([5,10,15,20,25])

In [29]:
print("15'ten büyükler: ", c[c>15])

15'ten büyükler:  [20 25]


In [33]:
# c>15 ifadesi şunu üretir:  [False, False, False,  True,  True]

In [34]:
# sonra c[c > 15 ] ise sadece True olan indexlerdekini elemanları alırız

In [36]:
print("10 veya 20 olanlar:", c[(c==10) | (c==20)])

10 veya 20 olanlar: [10 20]


In [37]:
print(c)

[ 5 10 15 20 25]


In [38]:
c_new = c[(c==10)|(c==20)]
print(c_new)

[10 20]


### Listeyle Seçim (Fancy indexing)

In [42]:
d = np.array([100, 200, 300, 400, 500])
indeksler = [0,2,4]
print("0,2,4. elemanlar:", d[indeksler])

0,2,4. elemanlar: [100 300 500]


### Örnekler

In [43]:
notlar = np.array([30,71,80,45])
print(notlar>70)

[False  True  True False]


In [45]:
sinifi_gecenler = notlar[notlar>70]
print(sinifi_gecenler)

[71 80]


In [48]:
print("Sınıfı gecenlerın sayısı:",sinifi_gecenler.size)

Sınıfı gecenlerın sayısı: 2
