# NumPy ile Matrislerde Dört İşlem

#### NumPy kullanarak toplama, çıkarma, çarpma ve bölme işlemleri

In [2]:
import numpy as np

In [3]:
# örnek matrislerimiz

In [8]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
print(A.shape, "  ", B.shape)

(2, 2)    (2, 2)


In [9]:
# Toplama (A+B)

In [10]:
toplam = A + B
print(toplam)

[[ 6  8]
 [10 12]]


In [11]:
# Çıkarma (A-B)

In [15]:
cikarma = A - B
print(cikarma)

[[-4 -4]
 [-4 -4]]


In [16]:
# Çarpma

In [17]:
# 1) Eleman Bazlı Çarpma : A * B

In [18]:
carpma_eleman_bazli = A * B
print(carpma_eleman_bazli)

[[ 5 12]
 [21 32]]


In [19]:
# 2) Matris Çarpımı (Lineer Cebir) : A @ B veya np.dot(A,B) 